development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_DEVELOPMENT"] %>
  event_logger_url: "https://pixel-path.multiwoven.com/trackr"
test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_TEST"] %>
  event_logger_url: "https://pixel-path.multiwoven.com/trackr"
production:
  secret_key_base: 253d6942a2e41541c4c8c55d352b5508ff0f4c1a5f9c5199f36f8ae95730f5a58a1c67184cb02933326a8996d2d1e27b96024fa497430f7f7e30ed3a74146d45
  event_logger_url: "https://pixel-path.multiwoven.com/trackr"